name: Canary Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    paths:
      - Libjector/**
  workflow_dispatch:
jobs:
  main:
    uses: dentolos19/ActionsPlayground/.github/workflows/REUSABLE-dotnet.yml@main
    with:
      TARGET_BRANCH: ${{ github.event.repository.default_branch }}
      PROJECT_FILE: Libjector.sln
      RELEASE_TAG: Canary